name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: sainathr19/backend 
      IMAGE_TAG: latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build the backend Docker image
      - name: Build backend Docker image
        run: |
          # Ensure Docker is running
          sudo service docker start

          # Build the Docker image
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t $IMAGE_NAME:$IMAGE_TAG .

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # 4. Push the backend image to Docker Hub
      - name: Push backend Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
