name: Deploy Backend to AWS EC2 with Docker
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build backend Docker image
        run: |
          cd survey-sphere-be
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t $DOCKER_USERNAME/survey-sphere-be:$IMAGE_TAG .
      
      - name: Docker Login
        run: |
          echo "Attempting to log in to Docker Hub"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          if [ $? -ne 0 ]; then
            echo "Docker login failed"
            exit 1
          fi
      
      - name: Push Docker Image
        run: |
          echo "Attempting to push image to Docker Hub"
          docker push $DOCKER_USERNAME/survey-sphere-be:$IMAGE_TAG
          if [ $? -ne 0 ]; then
            echo "Docker push failed"
            exit 1
          fi
      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          script: |
            # Pull the image with explicit path
            sudo docker pull ${{ env.IMAGE_NAME }}:latest
            # Run with explicit command
            sudo docker run -d \
            --name databases-performance-test \
            --restart always \
            -p 3000:3000 \
            --env-file /home/${{ env.EC2_USER }}/app.env \
            ${{ env.IMAGE_NAME }}:latest \
            /app/target/release/databases-performance-test
